import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./components/ReduxProvider";
import Authenticated from "./components/Authenticated";
import { CookiesProvider } from "next-client-cookies/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <CookiesProvider>
            <ReduxProvider>
                <html lang="en">
                    <body className={inter.className}>{children}</body>
                </html>
            </ReduxProvider>
        </CookiesProvider>
    );
}
